# Generated by Django 3.2.5 on 2021-08-06 11:29

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_gungu',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_sido',
            field=models.CharField(choices=[('', '미정'), ('서울', '서울특별시'), ('부산', '부산광역시'), ('인천', '인천광역시'), ('대구', '대구광역시'), ('광주', '광주광역시'), ('대전', '대전광역시'), ('울산', '울산광역시'), ('세종', '세종시'), ('경기', '경기도'), ('강원', '강원도'), ('충남', '충청남도'), ('충북', '충청북도'), ('경북', '경상북도'), ('경남', '경상남도'), ('전북', '전라북도'), ('전남', '전라남도'), ('제주', '제주도')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='career',
            field=models.CharField(choices=[('0', '1년 미만'), ('1', '1년'), ('2', '2년'), ('3', '3년'), ('4', '4년'), ('5', '5년'), ('6', '6년'), ('7', '7년'), ('8', '8년'), ('9', '9년'), ('10', '10년 이상')], default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Developer', '개발자'), ('Designer', '디자이너'), ('Planner', '기획자'), ('Etc', '그 외')], default='Etc', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, choices=[('', '미입력'), ('ATTENDING', '재학중'), ('ABSENCE', '휴학중'), ('SEARCHING', '구직중'), ('WORKING', '재직중')], default='', max_length=200),
        ),
    ]
