# Generated by Django 3.2.5 on 2021-08-08 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210804_1929'),
        ('users', '0003_alter_user_intro'),
    ]

    operations = [
    ]
