# Generated by Django 3.2.5 on 2021-08-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='image/users/profile_default.png', upload_to='image/users'),
        ),
    ]
