# Generated by Django 3.2.5 on 2021-08-10 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_0002_auto_20210804_1929_0003_alter_user_intro'),
        ('users', '0007_alter_user_image'),
    ]

    operations = [
    ]
