# Generated by Django 3.2.5 on 2021-08-10 23:20

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20210810_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='career',
            field=models.CharField(choices=[('0', '1년 미만'), ('1', '1년'), ('2', '2년'), ('3', '3년'), ('4', '4년'), ('5', '5년'), ('6', '6년'), ('7', '7년'), ('8', '8년'), ('9', '9년'), ('10', '10년 이상')], default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Developer', '개발자'), ('Designer', '디자이너'), ('Planner', '기획자'), ('Etc', '그 외')], default='Etc', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, choices=[('', '미입력'), ('ATTENDING', '재학중'), ('ABSENCE', '휴학중'), ('SEARCHING', '구직중'), ('WORKING', '재직중')], default='', max_length=200),
        ),
    ]
