# Generated by Django 3.2.5 on 2021-08-04 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_build', '0003_likerecruit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.TextField(max_length=100)),
                ('user_username', models.TextField(max_length=100)),
                ('content', models.TextField(max_length=200)),
                ('comment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team_build.comment')),
            ],
        ),
    ]
