# Generated by Django 3.2.5 on 2021-08-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_build', '0004_commentanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='image',
            field=models.ImageField(blank=True, default='image/team_build/img_default.png', upload_to='image/team_build/'),
        ),
    ]
