# Generated by Django 3.2.5 on 2021-08-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_build', '0004_commentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='writer_username',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='locate',
            field=models.CharField(blank=True, choices=[('', '미정'), ('서울', '서울특별시'), ('부산', '부산광역시'), ('인천', '인천광역시'), ('대구', '대구광역시'), ('광주', '광주광역시'), ('대전', '대전광역시'), ('울산', '울산광역시'), ('세종', '세종시'), ('경기', '경기도'), ('강원', '강원도'), ('충남', '충청남도'), ('충북', '충청북도'), ('경북', '경상북도'), ('경남', '경상남도'), ('전북', '전라북도'), ('전남', '전라남도'), ('제주', '제주도')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='service_level',
            field=models.CharField(blank=True, choices=[('0', '아이디어 구상 단계'), ('1', '초기 개발 단계'), ('2', '프로토타입 완성 단계'), ('3', '배포 및 상용화 단계'), ('4', '서비스 확장 단계')], default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='team_members',
            field=models.CharField(blank=True, choices=[('1', '1명'), ('2', '2명'), ('3', '3명'), ('4', '4명'), ('5', '5명 이상')], default='1', max_length=200),
        ),
    ]
