# Generated by Django 3.2.5 on 2021-08-10 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_build', '0005_auto_20210804_1909'),
        ('team_build', '0006_alter_recruit_image'),
    ]

    operations = [
    ]
