# Generated by Django 3.2.5 on 2021-08-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_build', '0007_merge_20210810_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='locate',
            field=models.CharField(blank=True, choices=[('', '미정'), ('서울', '서울특별시'), ('부산', '부산광역시'), ('인천', '인천광역시'), ('대구', '대구광역시'), ('광주', '광주광역시'), ('대전', '대전광역시'), ('울산', '울산광역시'), ('세종', '세종시'), ('경기', '경기도'), ('강원', '강원도'), ('충남', '충청남도'), ('충북', '충청북도'), ('경북', '경상북도'), ('경남', '경상남도'), ('전북', '전라북도'), ('전남', '전라남도'), ('제주', '제주도')], default='', max_length=2),
        ),
    ]
