# Generated by Django 3.2.5 on 2021-08-03 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeRecruit',
        ),
    ]
